# Generated by Django 6.0.2 on 2026-02-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_supperadmin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'restaurant'), (2, 'customer')], null=True),
        ),
    ]
