# Generated by Django 6.0.2 on 2026-02-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_supperadmin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_is_superadmin',
            new_name='is_superadmin',
        ),
    ]
