# Generated by Django 6.0.2 on 2026-02-04 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Motorbike'), ('truck', 'Truck')], max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('engine_number', models.CharField(max_length=50, unique=True)),
                ('registration_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='users.vehicle')),
            ],
        ),
    ]
