version: '3.8'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOST=localhost,127.0.0.1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on: 
      - pgdb
      - redis 
  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/django
    depends_on:
      - django
      - redis
  pgdb:
    image: postgres:17-alpine
    container_name: pgdb
    environment:
      POSTGRES_DB: student_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data/  
    ports:
    - "5432:5432"       
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"


volumes:
 pgdata:
